image: golang:1.10-alpine

stages:
  - test
  - build

before_script:
  - apk add --no-cache make git
  - mkdir -p /go/src/github.com/yannh
  - cp -r $CI_PROJECT_DIR /go/src/github.com/yannh/redis-dump-go
  - cd /go/src/github.com/yannh/redis-dump-go

test:
  stage: test
  script:
  - make test

build:
  stage: build
  script:
  - make build
  - cp redis-dump-go ${CI_PROJECT_DIR}/
  artifacts:
    paths:
    - redis-dump-go
